### ISSUE TITLE
Slots usage

### ISSUE THREAD

**Issue by anubra266** [kumaaa-inc/shadow-panda#116]
consider using slot recipes

**Comment by nanopx** [comment]
Thanks for the issue @anubra266  😄 

Slot recipes are coming soon 👍

**Comment by nanopx** [comment]
Just released [`v0.2.0`](https://github.com/kumaaa-inc/shadow-panda/releases/tag/%40shadow-panda%2Fpreset%400.2.0) which replaces most components to slot recipes 👍
